engines:
  eslint:
        enabled: true
        checks:
                no-eval:
                          enabled: false
                no-process-exit:
                          enabled: false
                global-require:
                          enabled: false
ratings:
    paths:
    - "lib/**/*"
exclude_paths:
- "tests/"
- "old_tests/"
- "boilerplate/"
- "demo/"
- "js/"
