environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "10"
cache:
 - "%LOCALAPPDATA%\\Yarn"
install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm --version
  - ps: |
      "installing IPFS"
      $IPFS_VER="0.4.18"
      pushd
      mkdir C:\Downloads | out-null; cd C:\Downloads
      Start-FileDownload "https://dist.ipfs.io/go-ipfs/v$($IPFS_VER)/go-ipfs_v$($IPFS_VER)_windows-amd64.zip"
      7z x .\go-ipfs*
      Remove-Variable IPFS_VER
      $ENV:PATH="C:\Downloads\go-ipfs;$ENV:PATH"
      popd
      ipfs init
  - ps: |
      "installing Yarn"
      $YARN_VER="1.12.3"
      Start-FileDownload "https://github.com/yarnpkg/yarn/releases/download/v$($YARN_VER)/yarn-$($YARN_VER).msi"
      cmd /c start /wait msiexec.exe /i "yarn-$($YARN_VER).msi" /quiet /qn /norestart
      rm "yarn-$($YARN_VER).msi"
      Remove-Variable YARN_VER
  - yarn --version
  - echo embark installation managed by package.json script 'ci'
test_script:
  - npm run ci:full
build: off
