module.exports = {
"ERC20Token": require('./ERC20Token').default,
"PluginStorage": require('./PluginStorage').default,
"StandardToken": require('./StandardToken').default,
"ZAMyLib2": require('./ZAMyLib2').default,
"ContractArgs": require('./ContractArgs').default,
"AnotherStorage": require('./AnotherStorage').default,
"SomeContract": require('./SomeContract').default,
"ZAMyLib": require('./ZAMyLib').default,
"SimpleStorageWithHttpImport": require('./SimpleStorageWithHttpImport').default,
"Test2": require('./Test2').default,
"SimpleStorageTest": require('./SimpleStorageTest').default,
"Ownable": require('./Ownable').default,
"SimpleStorage": require('./SimpleStorage').default,
"Test": require('./Test').default,
"AlreadyDeployedToken": require('./AlreadyDeployedToken').default,
"Token": require('./Token').default,
"MyToken2": require('./MyToken2').default,
"MyToken": require('./MyToken').default,

};